### ISSUE TITLE
Need details about util.py

### ISSUE THREAD

**Issue by Shubham-Kr-Shaw** [nikzagarwal/Project_21#25]
@nikzagarwal please send the details on which the util.py will be coded.

**Comment by nikzagarwal** [comment]
Should make a file that can take input data and save profile using pandas profiling and save in html form.
Try to use :
`pip install pandas-profiling[notebook]`
I have sent you a refrence file

**Comment by Shubham-Kr-Shaw** [comment]
OK, I'll do this job today as per your instructions.
